### ISSUE TITLE
Support for merge commits

### ISSUE THREAD

**Issue by roborourke** [tibdex/backport#34]
Hey, first off thanks for building this - it's so well crafted and it's been a huge time saver for us ❤️ 

When we updated to use the github action approach I noticed that merge commits always fail to backport successfully. If this change is intentional and by design then no worries but I'd love to get that functionality back if you're open to it.

I found that all I needed to do was a slight modification to the instructions it outputs, either `git cherry-pick` the individual commits in the PR or `git cherry-pick -m1 <merge commit>` for it to work.

Thanks again for your hard work - if you're open to the change I'll work on a PR for it.

**Comment by tibdex** [comment]
Hi Robert, thanks for the kind words. 

> If this change is intentional and by design.

It's not intentional, it's that I didn't need to support merge commits for my use cases since I use [Autosquash](https://github.com/marketplace/actions/autosquash) that always squashes and merges my pull requests. I would be OK adding support for backporting merge commits though.

**Comment by roborourke** [comment]
I ended up forking from the point in time before you switched to the current behaviour and setting up our own instance as we have a different to squash vs merge commits at work. I'll close this one out as it's not an itch you need to scratch or support - thanks again for building this tool!
